version: '3.8'

services:
  ai-chat:
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-gpt-4o-mini}
      - LLM_TEMPERATURE=${LLM_TEMPERATURE:-0.2}
    volumes:
      - .:/app
      # Volumes anônimos para evitar conflito com .chainlit no host
      - /app/ai_chat/.chainlit
    restart: unless-stopped

